import { ArrowUpRight } from 'lucide-react';
import { SiteLink } from '@/components/SiteLink';
import { InquiryForm } from '@/components/InquiryForm';
import { siteUrl } from '@/lib/site-config';

const offers = [
  { number: '01', title: 'Image.', text: 'Look like the man you want to be. Hair, skin, physique, wardrobe, and photos—with the right specialists to make it happen.', href: '/mens-image-consulting-los-angeles/', label: 'Your personal rebrand' },
  { number: '02', title: 'Connections.', text: 'A wider circle. More women you actually want to meet. I bring my LA network into your world through natural introductions and shared plans.', href: '/social-life-consulting-los-angeles/', label: 'The right people' },
  { number: '03', title: 'Experiences.', text: 'Nights out together. Private dinners. Parties worth going to. I make the plans, bring people together, and help you feel at home in the room.', href: '/private-events-los-angeles/', label: 'A better social calendar' },
];

export default function Home() {
  const schema = { '@context': 'https://schema.org', '@graph': [
    { '@type': 'Organization', '@id': siteUrl + '/#organization', name: 'Vantage', url: siteUrl, email: 'michael@vantagesocal.com', sameAs: ['https://www.instagram.com/vantagesocal/'], description: 'Private image and social concierge for men in Los Angeles, Orange County, and Ventura County.' },
    { '@type': 'Service', name: 'Private Image and Social Concierge', provider: { '@id': siteUrl + '/#organization' }, url: siteUrl, description: 'Personal rebranding, social connections, nights out, private dinners, and parties for men seeking a better dating and social life.', areaServed: ['Los Angeles County', 'Orange County', 'Ventura County'] },
  ] };
  return <>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema).replace(/</g, '\\u003c') }} />
    <SiteLink className="skip-link" href="#main">Skip to content</SiteLink>
    <header className="site-header"><SiteLink className="wordmark" href="/" aria-label="Vantage home">vantage<span>.</span></SiteLink><nav aria-label="Main navigation"><SiteLink href="/about/">About</SiteLink><SiteLink href="/services/">What I do</SiteLink><SiteLink href="/blog/">Field Notes</SiteLink><SiteLink href="#apply">Let’s talk</SiteLink></nav></header>
    <main id="main">
      <section className="brand-hero" aria-labelledby="hero-title">
        <img className="brand-hero-image" src="/vantage-social-hero.webp" alt="An evening gathering on a coastal terrace" width="1536" height="1024" fetchPriority="high" />
        <div className="brand-hero-copy"><p className="eyebrow">Image · Connections · Experiences</p><h1 id="hero-title">Let me build<br />your social life<br /><span>in LA.</span></h1><p>A sharper image. The right people. Better nights.<br />Your private social concierge.</p><SiteLink className="primary-link" href="#apply">Let’s make it happen <ArrowUpRight size={18} aria-hidden="true" /></SiteLink></div>
        <div className="brand-hero-bottom"><span>LOS ANGELES / SOUTHERN CALIFORNIA</span><SiteLink href="https://www.instagram.com/vantagesocal/" target="_blank" rel="noopener noreferrer">@vantagesocal <ArrowUpRight size={14} aria-hidden="true" /></SiteLink></div>
      </section>
      <section className="brand-intro brand-section" aria-labelledby="intro-title"><p className="eyebrow">Your life, with better company</p><div><h2 id="intro-title">You have the means.<br />Let’s build the life.</h2><p>You want to look your best, meet women you are excited about, and have a social life that is actually worth your time. I help make that happen.</p><p>I rebrand your image, connect you with the right people, and host events and nights out. We work together personally—like having a well-connected friend who knows LA and makes things happen.</p><span className="brand-proof">25+ men helped · Personal · Discreet</span></div></section>
      <section className="brand-offer brand-section" aria-labelledby="offer-title"><div className="brand-section-top"><p className="eyebrow">What I bring</p><h2 id="offer-title">The whole picture.<br />Handled personally.</h2></div><div className="brand-offer-grid">{offers.map((offer) => <article key={offer.number}><span>{offer.number}</span><h3>{offer.title}</h3><p>{offer.text}</p><SiteLink href={offer.href}>{offer.label} <ArrowUpRight size={16} aria-hidden="true" /></SiteLink></article>)}</div></section>
      <section className="brand-access brand-section" aria-labelledby="access-title"><p className="eyebrow">Better people. Better plans.</p><h2 id="access-title">Be part of the night.<br />Not on the outside of it.</h2><div><p>My network spans nightlife, hospitality, fashion, beauty, fitness, and entertainment. That can mean opportunities to meet models, influencers, creatives, and other interesting people when the connection makes sense.</p><p>We go out together. I help with introductions. We host dinners and parties. You meet people through the experience, with a friend beside you—not through a list of matches.</p></div><SiteLink className="primary-link" href="#apply">Build your social life <ArrowUpRight size={18} aria-hidden="true" /></SiteLink></section>
      <section className="brand-start brand-section" aria-labelledby="start-title"><div><p className="eyebrow">How it starts</p><h2 id="start-title">One conversation.<br />Your next chapter.</h2></div><ol><li><span>01</span><div><h3>Tell me what you want.</h3><p>Your look, your dating life, the people you want to meet, and what is missing.</p></div></li><li><span>02</span><div><h3>We make a plan.</h3><p>Every guy is different. We start where it will make the biggest difference for you.</p></div></li><li><span>03</span><div><h3>We get out there.</h3><p>The appointments, the people, the nights, the events. I stay involved.</p></div></li></ol></section>
      <section className="application-section brand-section" id="apply" aria-labelledby="apply-title"><div className="application-intro"><p className="eyebrow">Just between us</p><h2 id="apply-title">What do you want<br />your life to look like?</h2><p>Tell me a little about yourself. I read every inquiry personally.</p><p>For men ready to invest in their image, dating life, and social world.</p><div className="application-area">Los Angeles<br />Orange County<br />Ventura County</div><SiteLink className="instagram-link" href="https://www.instagram.com/vantagesocal/" target="_blank" rel="noopener noreferrer">Get the vibe on Instagram <ArrowUpRight size={16} aria-hidden="true" /></SiteLink></div><InquiryForm /></section>
    </main>
    <SiteLink className="floating-apply" href="#apply">Let’s talk <ArrowUpRight size={16} aria-hidden="true" /></SiteLink>
    <footer className="site-footer site-footer-expanded"><SiteLink className="wordmark" href="/">vantage<span>.</span></SiteLink><nav className="footer-links" aria-label="Footer navigation"><SiteLink href="/about/">About</SiteLink><SiteLink href="/services/">What I do</SiteLink><SiteLink href="/blog/">Field Notes</SiteLink><SiteLink href="https://www.instagram.com/vantagesocal/">Instagram</SiteLink><SiteLink href="/privacy/">Privacy</SiteLink></nav><p>Los Angeles · Orange County · Ventura County</p><span>© {new Date().getFullYear()} Vantage</span></footer>
  </>;
}
