import type { Metadata } from 'next';
import { BlogPostPage } from '@/components/BlogPostPage';
import { blogPosts } from '@/lib/blog';

const post = blogPosts[0];
export const dynamic = 'force-static';
export const metadata: Metadata = { title: `${post.title} | Vantage`, description: post.description, alternates: { canonical: `/blog/${post.slug}/` }, openGraph: { title: post.title, description: post.description, url: `/blog/${post.slug}/`, type: 'article', publishedTime: post.publishedIso } };

export default function Page() {
  return <BlogPostPage {...post}
    intro={[
      'Los Angeles can feel full and lonely at the same time. There are people everywhere, but distance, traffic, work schedules, and scattered neighborhoods make repeated contact harder than it looks. A social circle rarely appears because you attended one busy event. It grows when the same people see you often enough to know you.',
      'The goal is not to collect contacts. It is to build a week that naturally produces familiarity, invitations, friendships, and eventually introductions to more people. That requires a system, but it should still feel like a life—not a networking campaign.',
    ]}
    sections={[
      { heading: 'Start with geography, not popularity', paragraphs: ['Choose a social radius you can realistically maintain. A recurring plan fifteen minutes away is more useful than a fashionable event across the city that you attend once. In Los Angeles, proximity is part of compatibility because it determines whether people can make spontaneous plans.', 'Pick one or two neighborhoods that fit your schedule and the kind of life you want. Build enough repetition there that bartenders, trainers, hosts, regulars, and neighbors begin to recognize you. Familiarity lowers the friction of every future conversation.'], points: ['A neighborhood close to home', 'A second area near work or existing commitments', 'Places you can revisit at the same time each week', 'Enough variety to meet friends as well as dates'] },
      { heading: 'Choose recurring environments', paragraphs: ['One-off mixers can produce conversations, but recurring environments produce relationships. Classes, fitness communities, recreational leagues, volunteering teams, cultural memberships, and small professional or creative groups give people a reason to see one another again.', 'Choose activities you would still enjoy if you met nobody you wanted to date. That makes you more relaxed, keeps you coming back, and gives the connection a real foundation. The best environment is one where conversation is normal and participation is visible.'], points: ['Weekly rather than annual', 'Interactive rather than passive', 'Small enough to recognize regulars', 'Aligned with interests you can discuss naturally'] },
      { heading: 'Become a contributor', paragraphs: ['Social circles grow around people who make life easier and more enjoyable. Introduce two people who should know each other. Remember what someone mentioned last week. Invite a few people to continue the evening. Share a useful recommendation. Follow up when you said you would.', 'This does not require becoming the loudest person in the room. Reliability, warmth, and good judgment are more valuable. When people trust you to improve the plan rather than complicate it, invitations begin to arrive without being chased.'] },
      { heading: 'Move from acquaintance to actual friend', paragraphs: ['Most potential friendships stall after a pleasant conversation. The missing step is a specific, low-pressure follow-up. “We should hang out” creates no plan. “A few of us are getting dinner in Los Feliz Thursday—want to join?” gives the relationship somewhere to go.', 'Keep the first invitation easy. A coffee, workout, casual dinner, gallery opening, or small group plan is enough. Friendship grows through repeated shared experience, not a single deep conversation.'] },
      { heading: 'Host before you feel ready', paragraphs: ['You do not need a mansion or a hundred-person guest list. Start with four to eight people and a reason to gather: dinner, a game, a fight, a tasting, a birthday, or drinks before an event. Invite people from different parts of your life who are likely to enjoy one another.', 'Hosting changes your position. You stop waiting for access and begin creating it. Good hosts are remembered, introduced, and included. Focus on the mix of people, clear logistics, and making each guest feel connected to someone else.'] },
      { heading: 'Build a weekly social operating system', paragraphs: ['A useful week has a balance of recurring rooms, direct invitations, and open space for spontaneous plans. Put social commitments on the calendar before work expands to consume everything. Track who you enjoyed meeting and follow up while the interaction is still fresh.', 'Give the system eight to twelve weeks. A social circle compounds slowly, then suddenly. One friend leads to a dinner, the dinner leads to a birthday, and the birthday introduces an entirely new group. Consistency creates the luck people often mistake for charisma.'], points: ['One recurring community', 'One plan you initiate', 'One invitation you accept', 'Two thoughtful follow-ups', 'One open evening for spontaneity'] },
    ]}
  />;
}
