import type { Metadata } from 'next';
import { BlogPostPage } from '@/components/BlogPostPage';
import { blogPosts } from '@/lib/blog';

const post = blogPosts[1];
export const dynamic = 'force-static';
export const metadata: Metadata = { title: `${post.title} | Vantage`, description: post.description, alternates: { canonical: `/blog/${post.slug}/` }, openGraph: { title: post.title, description: post.description, url: `/blog/${post.slug}/`, type: 'article', publishedTime: post.publishedIso } };

export default function Page() {
  return <BlogPostPage {...post}
    intro={[
      'Meeting people without dating apps is less about finding a secret venue and more about building a life where conversation and repeated contact happen naturally. Los Angeles has endless options, but random motion is not the same as social momentum.',
      'A better offline dating life comes from three channels working together: places where you become a regular, events where interaction is expected, and a social circle that keeps introducing new people. You do not need to approach everyone. You need to become comfortable, visible, and connected in the right environments.',
    ]}
    sections={[
      { heading: 'Stop looking for one perfect place', paragraphs: ['No bar, gym, neighborhood, or event guarantees that you will meet someone compatible. A place can be full of attractive people and still be a poor setting for natural conversation. Judge an environment by whether people mingle, return, bring friends, and have a reason to talk.', 'Build a small portfolio of environments instead: one recurring activity, one social venue where you know the rhythm, and one event-based channel. This gives you multiple ways to meet people without turning every outing into a mission.'] },
      { heading: 'Use repeated contact to your advantage', paragraphs: ['People are more open when you are familiar. The second conversation is easier than the first, and the fifth can feel effortless. Choose a coffee shop, fitness studio, neighborhood restaurant, members community, or cultural venue you genuinely like and appear consistently.', 'Talk to everyone, not only people you want to date. Staff, couples, regulars, and other men all expand your comfort and your network. A person who is not a romantic possibility may eventually invite you into the room where you meet someone who is.'] },
      { heading: 'Pick environments with built-in interaction', paragraphs: ['The easiest places to meet people give you a shared subject and a natural next sentence. Group dinners, recreational sports, workshops, volunteer teams, tastings, gallery events, live performances with an intermission, and friend-hosted gatherings all create context.', 'Passive environments are harder. Sitting alone in a loud room and hoping something happens creates pressure. Choose places where movement, participation, and conversation are already part of the format.'], points: ['Small group events', 'Recurring classes or leagues', 'Volunteer work with a consistent team', 'Dinners and gatherings hosted by friends', 'Cultural and hospitality events with natural pauses'] },
      { heading: 'Start conversations like a normal person', paragraphs: ['Use what is already happening. Ask a simple question, make an observation, or request an opinion that fits the moment. The aim is to discover whether conversation feels mutual, not to force an outcome.', 'Pay attention to engagement. If someone turns toward you, asks questions back, and contributes, keep talking. If the answers are short or attention returns elsewhere, exit gracefully. Good social judgment is more attractive than persistence.'] },
      { heading: 'Make the next step easy', paragraphs: ['When a conversation is going well, do not wait for a perfect ending. Suggest a simple continuation that matches what you discussed: another event, a coffee nearby, joining a group plan, or exchanging contact information.', 'Keep it direct and light. You are offering an opportunity, not demanding an answer. If the interest is not mutual, accept it cleanly and keep enjoying your evening. That confidence protects everyone’s comfort and makes you better socially.'] },
      { heading: 'Let your social life do more of the work', paragraphs: ['The strongest offline dating channel is often a healthy social life. Friends provide context, trust, invitations, and introductions. They also make you a more relaxed person because every night does not depend on meeting a romantic prospect.', 'Invest in friendships and become someone who organizes good plans. Host a dinner. Bring two groups together. Invite the new acquaintance. Over time, meeting potential partners becomes a natural byproduct of a connected life instead of a separate weekly task.'] },
      { heading: 'A realistic four-week starting plan', paragraphs: ['Week one is for choosing two recurring environments and reconnecting with three people you already know. Week two is for attending both environments and initiating one small plan. Week three is for returning, following up, and accepting an invitation you might normally decline. Week four is for hosting a simple dinner or drinks.', 'The objective is not a date by day thirty. It is a system that can keep producing friends, invitations, confidence, and introductions long after the month ends.'], points: ['Two recurring environments', 'Three reconnection messages', 'One plan you organize', 'One plan you accept', 'One small gathering you host'] },
    ]}
  />;
}
